### ISSUE TITLE
个人账户能加我进项目组么？

### ISSUE THREAD

**Issue by qq83387856** [iVanilla/hydroght#1]
好像是要建一个组织才能加人吧

**Comment by iVanilla** [comment]
可以给你Collaborators的权限，这样你就可以提交修改了。

**Comment by qq83387856** [comment]
我的QQ 83387856 可以建个项目组的QQ群

**Comment by iVanilla** [comment]
@qq83387856 我已经不怎么用QQ了，倾向于微信，电子邮件也可以（precomx@live.com）。

**Comment by iVanilla** [comment]
这个月4~11号由于家里线路问题一直无法上网，所以那几天我没有继续做，但直到现在也联系不到你，包括微信、Email、你的博客留言板都没有回复。
